#!/command/with-contenv bash
# shellcheck shell=bash

# svc-crond main
main() {
    # This will prepend service name to all output from here
    exec > >(while read line; do echo "[svc-crond] ${line}"; done) 2>&1

    if [[ "${CRON_ENABLED}" == "false" || "${CRON_ENABLED}" == "0" ]]
    then
        echo "CRON_ENABLED is set to false. Service disabled"
        sleep infinity
    fi

    echo "Starting cron daemon"
    s6-envdir /run/secrets_normalized /usr/sbin/crond -f -l 2
}
main
