#!/usr/bin/with-contenv sh
set -e

fix_permissions() {
    /usr/local/bin/attr /var/www true www-data:www-data 0770 2771 &
    /usr/local/bin/attr /var/www/html/wp-content true www-data:www-data 2755 2755 &
}

main() {
    local counter=1
    fix_permissions &
    pid=$!

    # Print status message every ~5 seconds
    while kill -0 $pid 2>/dev/null; do
        if [ $((counter % 5)) -eq 0 ]; then
            echo "> Process \"99-webuser-permissions\" hasn't finished yet [${counter}]"
        fi

        counter=$((counter + 1))
        sleep 1
    done
}

main &